# DNS zones configuration
# This file allows configuring fallback and test zones
# without modifying the source code

# Fallback zones used when automatic discovery fails
fallback_zones:
  - localhost
  - 127.in-addr.arpa
  - local

# Test zones for DNS discovery (when SSH is not available)
test_zones:
  - localhost
  - 127.in-addr.arpa
  - local
  - 1.168.192.in-addr.arpa

# System zones to ignore during automatic discovery
system_zones:
  - localhost
  - 127.in-addr.arpa
  - 0.in-addr.arpa
  - 255.in-addr.arpa
  - root.hint
  - hint
  - "."
  - cache
  - bind
  - version.bind
  - hostname.bind

# DNS discovery configuration
discovery:
  # Maximum number of subdomains to test
  max_subdomains: 50
  
  # Timeout for DNS queries in seconds (réduit pour des réponses plus rapides)
  dns_timeout: 1
  
  # Enable/disable subdomain discovery
  enable_subdomain_discovery: true
  
  # Enable/disable DNS walking
  enable_dns_walking: true 