apiVersion: v2
name: dns-manager
description: Interface web pour la gestion des enregistrements DNS BIND
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - dns
  - bind
  - web-interface
  - flask
home: https://github.com/your-repo/dns-manager
maintainers:
  - name: Solal
    email: solal@pandata.ninja