# Configuration par défaut pour le DNS Manager

# Configuration de l'image
image:
  repository: dns-manager
  pullPolicy: IfNotPresent
  tag: "latest"

# Configuration du déploiement
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# Configuration du service
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Configuration de l'ingress
ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: dns.solal.internal
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dns-manager-tls
      hosts:
        - dns.solal.internal

# Configuration des ressources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Configuration des probes
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  timeoutSeconds: 3
  periodSeconds: 5
  failureThreshold: 3

# Configuration du compte de service
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Configuration de sécurité
podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

# Configuration des noeuds
nodeSelector: {}

tolerations: []

affinity: {}

# Configuration de l'application
app:
  # Configuration DNS
  dnsServer: "192.168.1.201"
  
  # Configuration Flask
  flask:
    secretKey: "change-this-secret-key-in-production"
    debug: false
    
  # Configuration des logs
  logging:
    level: "INFO"

# Persistence pour les logs (optionnel)
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# Configuration des variables d'environnement
env:
  - name: FLASK_ENV
    value: "production"
  - name: PYTHONUNBUFFERED
    value: "1" 